---
# tasks file for itigo.packages

- name: 'linux : get the package facts'
  package_facts:
  tags:
    - configuration
    - packages

- name: "linux : install application"
  package:
    name: "{{ item.key }}"
    state: "{{ 'latest' if item.value.version == 'latest' else 'present' }}"
  with_dict:
    - "{{ packages }}"
  when: >
      not ( packages_var_lower | json_query(packages_var_query)) or
      item.value.version != 'latest'
  vars:
    packages_var_query: '[?package==`{{ item.key | lower }}`]'
    packages_var_lower: "{{ ansible_facts.packages | lower }}"
  tags:
    - packages
