---
# tasks file for itigoag.packages

- name: 'windows : ensure facts of chocolatey'
  win_chocolatey_facts:
  tags:
    - configuration
    - packages

- name: 'windows : include install tasks'
  include_tasks: choco/install.yml
  loop: '{{ packages | dict2items }}'
  loop_control:
    loop_var: loop_choco
  when: >
    not ( packages_var_lower | json_query(packages_var_query)) or
    loop_choco.value.version != 'latest'
  vars:
    packages_var_query: '[?package==`{{ loop_choco.key | lower }}`]'
    packages_var_lower: '{{ ansible_chocolatey.packages | lower }}'
  tags:
    - packages
